import_from_git(url: 'https://github.com/marcelo-schroeder/IFAFastfile.git')

platform :ios do

  desc "Update Cocoapods and Carthage dependencies"
  lane :updateDependencies do
    cocoapods
  end

end